config/routes.rb
Rails.application.routes.draw do
	devise_for :users
	resources :posts do
		resources :comments
	end

	root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :comments

	has_attached_file :image, styles: { large: "600x600>", medium: "300x300>", thumb: "150x150#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	# Uses a method from Devise to force the user to login before any action other than view index and show pages
	before_action :authenticate_user!, except: [:index]

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:comment))
		@comment.user_id = current_user.id if current_user
		@comment.save

		if @comment.save
			redirect_to post_path(@post)
		else
			render 'new'
		end
	end

	def edit
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
	end

	def update
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])

		if @comment.update(params[:comment].permit(:comment))
			redirect_to post_path(@post)
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy
		redirect_to post_path(@post)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	# calls the method find_post before the show, edit, update and destroy methods
	# DRY Principle
	before_action :find_post, only: [:show, :edit, :update, :destroy]

	# Uses a method from Devise to force the user to login before any action other than view index and show pages
	before_action :authenticate_user!, except: [:index, :show]
	
	# Creates the index method
	def index
		@posts = Post.all.order("created_at DESC")
	end

	# Shows the post
	def show	
	end

	# Creates the new post view
	def new
		@post = current_user.posts.build
	end

	# Creates the new post
	def create
		# Gets the parameters for the new post
		@post = current_user.posts.build(post_params)

		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	# Creates the edit view
	def edit
	end

	# Updates the post
	def update
		if @post.update(post_params)
			redirect_to @post
		else
			render 'edit'
		end
	end

	# Deletes the post
	def destroy
		@post.destroy
		redirect_to root_path
	end

	# Methods bellow are private
	private

	# Finds a specific post
	def find_post
		@post = Post.find(params[:id])
	end

	# Gets the title and content of the post (DRY Principle)
	def post_params
		params.require(:post).permit(:title, :content, :image)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.haml
.comment.clearfix
	.content
		%p.comment_content= comment.comment
		%p.comment_author= comment.user.email
	- if current_user != NIL && current_user.id == comment.user.id
		.buttons
			= link_to "Edit", edit_post_comment_path(comment.post, comment)
			= link_to "Delete", [comment.post, comment], method: :delete, data: {confirm: "Are you sure?" }

app/views/comments/_form.html.haml
= simple_form_for([@post, @post.comments.build]) do |f|
	= f.input :comment
	= f.submit

app/views/comments/edit.html.haml
#edit_post
	%h1 Edit Reply

	= simple_form_for([@post, @comment]) do |f|
		= f.input :comment
		= f.submit
		= link_to "Cancel", post_path(@post), class: "cancel_button"

app/views/layouts/application.html.haml
!!!
%html
%head
  %title Full Stack Forum
  = csrf_meta_tags
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  %link{ rel: "stylesheet", href: "https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" }
  %link{:rel => "stylesheet", :href => "https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css" }
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
%body
  %header.main_header.clearfix
    .wrapper
      #logo
        %p= link_to "Full Stack Forum", root_path
      #buttons
        - if user_signed_in?
          = link_to "New Topic", new_post_path
        - else
          = link_to "Sign Up", new_user_registration_path
          = link_to "Sign In", new_user_session_path

  .wrapper
    %p.notice= notice
    %p.alert= alert

  .wrapper
    = yield

app/views/posts/_form.html.haml
= simple_form_for @post do |f|
	= f.input :title
	= f.input :image, as: :file
	= f.input :content
	= f.submit

app/views/posts/edit.html.haml
#edit_post
	%h1 Edit Post

	= render 'form'

	= link_to "Cancel", post_path, class: "cancel_button"

app/views/posts/index.html.haml
#posts
	- @posts.each do |post|
		.post
			%h2.title= link_to post.title, post
			%p.details
				Published
				= time_ago_in_words(post.created_at)
				by
				= post.user.email

app/views/posts/new.html.haml
#add_post
	%h1 New Topic

	= render 'form'

app/views/posts/show.html.haml
#post_content
	%h1= @post.title
	- if @post.image?
		= image_tag @post.image.url(:medium)
	%p= @post.content
	- if current_user != NIL && current_user.id == @post.user.id
		= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to do this?"}, class: "button"
		= link_to "Edit", edit_post_path(@post), class: "button"

	%br/
	%br/
	%hr/

	#comments
		%h3
			= @post.comments.count 
			Comments
		= render @post.comments

		%h3 Reply to thread
		= render "comments/form"